C4Component
    Component(frontend, "Web UI", "HTML, CSS, Vanilla JavaScript, Vanilla", "Enables the user to interact from the browser with the Sand Castle services.")
    
    Container_Boundary(backend, "Backend") {
        Component(c_module, "Recovery token module", "C-based shared object", "Generates recovery tokens.")
        Component(api, "Web API", "Python 3, Flask", "Responds to API requests.")
        Component(pam, "Linux Authenticator", "Linux Pluggable Authentication Modules", "Checks the credentials of a user.")
    }

    Rel(frontend, api, "API requests", "HTTP")
    UpdateRelStyle(frontend, api, $offsetY="-60", $offsetX="-20")

    Rel(api, c_module, "Generation requests", "Function calling")
    UpdateRelStyle(api, c_module, $offsetY="50", $offsetX="-40")

    Rel(api, pam, "Authentication requests", "Function calling")
    UpdateRelStyle(api, pam, $offsetY="50", $offsetX="-70")
