%%{init: {"theme": "neutral", "flowchart": {"htmlLabels": true}}}%%

flowchart LR

%% Class definition

classDef service fill:#3498db
classDef tool-service fill:#3498db,stroke:#333,stroke-width:3px,stroke-dasharray: 5 5
classDef tool stroke:#333,stroke-width:3px,stroke-dasharray: 5 5
classDef legend fill:#ecf0f1

%% Objects

subgraph portrait[Ubuntu Portrait]
    portrait-codebase[(Codebase)]:::service
    portrait-demo[Live demo]:::service
end

subgraph threat-modelling[Threat modelling]
    dragon[OWASP Threat Dragon]:::tool-service
end

threat-model[(Threat model)]

threat-modelling -->|produces| threat-model

portrait -->|is analysed in| threat-modelling

subgraph tool_run[Tools run and aggregation]
    subgraph static-analysers[Static analysers]
        osv-scanner[OSV-Scanner]:::tool-service
        gitleaks[Gitleaks]:::tool-service
        flawfinder[flawfinder]:::tool-service
        bandit[Bandit]:::tool-service
        Semgrep[Semgrep]:::tool-service
    end

    class static-analysers service

    sast-warnings[(SARIF warnings)]
    crashes[(Crashes)]
    flaws[(Flaws)]
    aflplusplus[AFL++]:::tool-service
    klee[KLEE]:::tool-service

    static-analysers -->|produces| sast-warnings
    aflplusplus -->|produces| crashes
    klee[KLEE]:::tool-service -->|produces| flaws
end

triaging[Triaging]
validation[Validation]
vulnerabilities[(Vulnerabilities)]

threat-model -->|informs| tool_run
tool_run --> triaging --> validation --> vulnerabilities

subgraph legend[Legend]
    service[Docker Compose service]:::service
    tool[Analysis tool]:::tool
end

class legend legend